config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def index
   @books = Book.all
 end

 def new
   @book = Book.new

 end

 def create
   @book = Book.new
   @book.update_attributes(name: params[:book][:name] , author: params[:book][:author])
   if @book.save
     redirect_to books_path
   else
     render :new


   end
 end

 def update
   @book = Book.find(params[:id])
   @book.update_attributes(name: params[:book][:name] , author: params[:book][:author])
   if @book.save
     redirect_to books_path
   else
     render :edit
   end

 end

 def destroy
 end

 def edit
   @book = Book.find(params[:id])

 end

 def show
    @book = Book.find(params[:id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<h1> Add a new book </h1>
<%= form_for(book, url: url_for(controller:"books" , action:"update" , id: book.id), method: :put) do |f| %>
<div>
  <label>Name</label>
  <%= f.text_field :name %>
</div>

<div>
  <label>Author</label>
  <%= f.text_field :author %>
</div>

<button type ="submit">Submit</button>

<% end %>

app/views/books/create.html.erb
Successfull !

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', book_path(@book.id) %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1> Listing all books </h1>
<% @books.each do |book| %>

   <p><%= book.id %> ,<%= book.name %>,<%= book.author %></p>

<% end %>

app/views/books/new.html.erb
<h1> Add a new book </h1>
<%= form_for(Book.new, url: url_for(controller:"books" , action:"create"), method: :post) do |f| %>
<div>
  <label>Name</label>
  <%= f.text_field :name %>
</div>

<div>
  <label>Author</label>
  <%= f.text_field :author %>
</div>

<% end %>

<button type ="submit">Submit</button>

app/views/books/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(id: @book.id) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>